khatamanquran/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kloter.urls')),
]

kloter/urls.py
from django.urls import path

from . import views

app_name = 'kloter'

urlpatterns = [
    path('<int:kloter>', views.render_kloter, name="kloter"),
    path('', views.index, name='index'),
    path('kloter/', views.list_kloter, name="list_kloter"),
    path('addkloter/', views.addkloter, name="addkloter"),
    path('addperson/', views.addperson, name="addperson"),
    path('editperson/<int:id>', views.editperson, name="editperson"),
    path('updateperson/<int:id>', views.updateperson, name="updateperson"),
    path('selesai/<int:id>', views.selesai, name="selesai"),
    path('belumselesai/<int:id>', views.belumselesai, name="belumselesai"),
    path('resetjuz/<int:kloter>', views.resetjuz, name="resetjuz"),
    path('resetputaran/<int:kloter>', views.resetputaran, name="resetputaran"),
    path('formperson/', views.formperson, name="formperson"),
    path('newjuz/<str:kloter>', views.new_juz, name="newjuz"),
    path('delete/<int:id>', views.deleteperson, name="deleteperson"),
]

kloter/models.py
from django.db import models

class Person(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    no_juz = models.IntegerField()
    nomer_kloter = models.IntegerField()
    ronde = models.IntegerField()
    telepon = models.TextField(max_length=20)
    selesai = models.BooleanField(default=False)

class NumberKloter(models.Model):
    kloter_number = models.IntegerField()
    ronde = models.IntegerField()

kloter/forms.py
from django import forms
from .models import Person

class PersonForm(forms.Form):
    name_attrs = {
        'id': 'id_name',
        'type': 'text',
		'class': 'form-input',
		'placeholder': 'Masukan nama'
    }

    no_juz_attrs = {
        'id': 'id_no_juz',
        'type': 'text',
        'class': 'form-input',
        'placeholder': 'Masukan juz ke berapa'
    }

    nomer_kloter_attrs = {
        'id': 'id_nomer_kloter',
        'type': 'text',
        'class': 'form-input',
        'placeholder': 'Masukan kloter'
    }

    telepon_attrs = {
        'id': 'id_telepon',
        'type': 'text',
        'class': 'form-input',
        'placeholder': 'Masukan nomer telepon'
    }



    name = forms.CharField(required=True, widget=forms.TextInput(attrs=name_attrs))
    no_juz = forms.IntegerField(required=True, widget=forms.NumberInput(attrs=no_juz_attrs))
    nomer_kloter = forms.IntegerField(required=True, widget=forms.NumberInput(attrs=nomer_kloter_attrs))
    telepon = forms.CharField(required=True, widget=forms.TextInput(attrs=telepon_attrs))

kloter/views.py
from django.http import HttpResponse
from django.http import response
from django.http.response import FileResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import NumberKloter
from .models import Person
from .forms import PersonForm
from datetime import date


def index(request):
    response = {}
    number = len(NumberKloter.objects.all())
    response['kloter_number'] = str(number)
    return render(request, 'dashboard.html', response)

def list_kloter(request):
    response = {}
    number = NumberKloter.objects.all()
    response['kloter_number2'] = number
    return render(request, 'listkloter.html', response)

def addkloter(request):
    new_kloter = NumberKloter(kloter_number=len(NumberKloter.objects.all())+1, ronde=1)
    new_kloter.save()
    return HttpResponseRedirect('/kloter/')

def render_kloter(request, kloter):
    response = {}
    persons = Person.objects.filter(nomer_kloter=kloter)
    persons = [obj for obj in persons]
    persons_selesai = Person.objects.filter(selesai=True, nomer_kloter=kloter)
    persons_belum_selesai = Person.objects.filter(selesai=False, nomer_kloter=kloter)
    persons_belum_selesai = [obj for obj in persons_belum_selesai]
    jumlah_selesai = 0
    for i in persons:
        if i.selesai:
            jumlah_selesai = jumlah_selesai + 1

    persons.sort(key=lambda x: x.no_juz)
    persons_belum_selesai.sort(key=lambda x: x.no_juz)

    response['selesai'] = jumlah_selesai
    list_number = [i for i in range(1, len(persons)+1)]
    periode = NumberKloter.objects.get(kloter_number=kloter)
    response['persons'] = persons
    response['persons_selesai'] = persons_selesai
    response['persons_belum_selesai'] = persons_belum_selesai
    list_number_belum_selesai = [i for i in range(1, len(persons_belum_selesai)+1)]
    response['list_number_belum_selesai'] = list_number_belum_selesai
    response['list_number'] = list_number
    response['periode'] = periode
    response['tanggal'] = date.today()

    return render(request, 'kloter.html', response)


def new_juz(request, kloter):
    periode = NumberKloter.objects.get(kloter_number=kloter)
    periode.ronde = periode.ronde + 1
    periode.save()
    persons = Person.objects.filter(nomer_kloter=int(kloter))
    persons = [obj for obj in persons]
    persons.sort(key=lambda x: x.no_juz)
    for i in persons:
        i.selesai = False
        i.save()
    temp_name = ""
    temp_no_telp = ""
    if len(persons) > 2:
        temp_name = persons[0].name
        temp_no_telp = persons[0].telepon
        persons[0].name = persons[len(persons)-1].name
        persons[0].telepon = persons[len(persons)-1].telepon
        persons[0].save()
        for i in range(len(persons)-1):
            temp1 = persons[i+1].name
            temp2 = persons[i+1].telepon

            persons[i+1].name = temp_name
            persons[i+1].telepon = temp_no_telp
            persons[i+1].save()
            temp_name = temp1
            temp_no_telp = temp2



            
    

    return HttpResponseRedirect('/' + str(kloter))

def formperson(request):
    response = {}
    response['person_form'] = PersonForm
    return render(request, 'formtambah.html', response)

def addperson(request):
    response = {}
    form = PersonForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['no_juz'] = int(request.POST['no_juz'])
        response['nomer_kloter'] = int(request.POST['nomer_kloter'])
        response['telepon'] = request.POST['telepon']
        periode = NumberKloter.objects.get(kloter_number=response['nomer_kloter'])
        person = Person(name=response['name'], no_juz=response['no_juz'], nomer_kloter=response['nomer_kloter'], ronde=periode.ronde, telepon=response['telepon'])
        person.save()
        return HttpResponseRedirect('/' + str(response['nomer_kloter']))
    else:
        return HttpResponseRedirect('/')

def editperson(request, id):
    response = {}
    response['no_id'] = id
    obj = Person.objects.get(id=id)
    response['data_person'] = obj
    form = PersonForm(initial={'name': obj.name, 'no_juz': obj.no_juz, 'nomer_kloter': obj.nomer_kloter, 'telepon': obj.telepon})
    response['person_form'] = form
    return render(request, 'editperson.html', response)

def updateperson(request, id):
    response = {}
    form = PersonForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['no_juz'] = int(request.POST['no_juz'])
        response['nomer_kloter'] = int(request.POST['nomer_kloter'])
        response['telepon'] = request.POST['telepon']
        person = Person.objects.get(id=id)
        person.name = response['name']
        person.no_juz = response['no_juz']
        person.nomer_kloter = response['nomer_kloter']
        person.ronde = response['nomer_kloter']
        person.telepon = response['telepon']
        person.save()
        return HttpResponseRedirect('/' + str(response['nomer_kloter']))
        
    else:
        return HttpResponseRedirect('/')

def deleteperson(request, id):
    response={}
    person = Person.objects.get(id = id)
    kloter = person.nomer_kloter
    person.delete()
    return HttpResponseRedirect('/' + str(kloter))

def resetjuz(request, kloter):
    persons = Person.objects.filter(nomer_kloter=int(kloter))
    list_number = [i for i in range(1, len(persons)+1)]
    for i in range(len(persons)):
        t = persons[i]
        t.no_juz = list_number[i]
        t.save()
    return HttpResponseRedirect('/' + str(kloter))

def resetputaran(request, kloter):
    putaran = NumberKloter.objects.filter(kloter_number=int(kloter))
    persons = Person.objects.filter(nomer_kloter=int(kloter))
    for i in range(len(persons)):
        x = persons[i]
        x.selesai = False
        x.save()
    t = putaran[0]
    t.ronde = 1
    t.save()

    return HttpResponseRedirect('/' + str(kloter))


def selesai(request, id):
    person = Person.objects.get(id = id)
    kloter = person.nomer_kloter
    persons = Person.objects.filter(nomer_kloter=int(kloter))
    for i in range(len(persons)):
        if persons[i].id == id:
            t = persons[i]
            t.selesai = True
            t.save()
        else:
            last = persons[i].selesai
            t = persons[i]
            t.selesai = last
            t.save()
    return HttpResponseRedirect('/' + str(kloter))

#belum
def belumselesai(request, id):
    person = Person.objects.get(id = id)
    kloter = person.nomer_kloter
    persons = Person.objects.filter(nomer_kloter=int(kloter))
    for i in range(len(persons)):
        if persons[i].id == person.id:
            t = persons[i]
            t.selesai = False
            t.save()
        else:
            last = persons[i].selesai
            t = persons[i]
            t.selesai = last
            t.save()
    return HttpResponseRedirect('/' + str(kloter))

kloter/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Mali:wght@500&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Mali:wght@500&family=Poppins&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css'%}">
</head>
<body style="margin:0;">
	<h1 style="color: #009DAE;" class="judul-page">Khotmul Qur'an</h1>
    <div style="margin-left: 700px; margin-top: 50px;"><a href="{% url 'kloter:list_kloter' %}"><button type="button" class="btn btn-primary btn-lg">Masuk</button></a></div>	
</body>
</html>

kloter/templates/editperson.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>List Kloter</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Mali:wght@500&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Mali:wght@500&family=Poppins&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/formtambah.css'%}">
</head>
<body style="margin:0;">
	<h1 style="color: #009DAE;" class="judul-page">Khotmul Qur'an</h1>
    <form action="{% url 'kloter:updateperson' no_id %}" method="POST" style="font-size: 20px;">
        {% csrf_token %}
		<div style="display: flex; margin-left: 30px; margin-top: 30px">
			<p class="label-form">Nama : </p>
        	{{ person_form.name }}
		</div>
		<div style="display: flex; margin-left: 30px; margin-top: 30px">
			<p class="label-form">No Juz : </p>
        	{{ person_form.no_juz }}
		</div>
		<div style="display: flex; margin-left: 30px; margin-top: 30px">
			<p class="label-form">No Kloter : </p>
        	{{ person_form.nomer_kloter }}
		</div>
		<div style="display: flex; margin-left: 30px; margin-top: 30px">
			<p class="label-form">Telepon : </p>
        	{{ person_form.telepon }}
		</div>
        <input id="submit" type="submit" value="Simpan" class="btn btn-primary button-post" style="color:white; margin-left: 200px; margin-top: 30px; font-size: 15px;">
    </form>
	<div style="margin-top: 50px;"><a style="text-decoration: none; margin-left: 50px;" href="{% url 'kloter:list_kloter' %}">< Kembali</a></div>
</body>
</html>

kloter/templates/formtambah.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>List Kloter</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Mali:wght@500&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Mali:wght@500&family=Poppins&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/formtambah.css'%}">
</head>
<body style="margin:0;">
	<h1 style="color: #009DAE;" class="judul-page">Khotmul Qur'an</h1>
    <form action="{% url 'kloter:addperson' %}" method="POST" style="font-size: 20px;">
        {% csrf_token %}
		<div style="display: flex; margin-left: 30px; margin-top: 30px">
			<p class="label-form">Nama : </p>
        	{{ person_form.name }}
		</div>
		<div style="display: flex; margin-left: 30px; margin-top: 30px">
			<p class="label-form">No Juz : </p>
        	{{ person_form.no_juz }}
		</div>
		<div style="display: flex; margin-left: 30px; margin-top: 30px">
			<p class="label-form">No Kloter : </p>
        	{{ person_form.nomer_kloter }}
		</div>
		<div style="display: flex; margin-left: 30px; margin-top: 30px">
			<p class="label-form">Telepon : </p>
        	{{ person_form.telepon }}
		</div>
        <input id="submit" type="submit" value="Simpan" class="btn btn-primary button-post" style="color:white; margin-left: 200px; margin-top: 30px; font-size: 15px;">
    </form>
	<div style="margin-top: 50px;"><a style="text-decoration: none; margin-left: 50px;" href="{% url 'kloter:list_kloter' %}">< Kembali</a></div>
</body>
</html>

kloter/templates/kloter.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>List Kloter</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Mali:wght@500&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Mali:wght@500&family=Poppins&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script type="txt/javascript" src="{% static 'js/kloter.js'%}"></script>
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script src="sweetalert2.min.js"></script>
	<link rel="stylesheet" href="sweetalert2.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/kloter.css'%}">

</head>
<body style="margin:0;">
	<h1 style="color: #009DAE;" class="judul-page">Khotmul Qur'an</h1>
	<div class="container-page">
		<div class="header-page" style="width: 350px;">
			<div style="display: flex;">
				<h4 id="no_kloter" style="font-weight: bold;">Kloter {{ periode.kloter_number }}</h4>
				<h5 style="margin-left: 50px; color: #db3b63;">{{ tanggal }}</h5>
			</div>
			<h5 style="margin-top: 20px;">Saat ini khataman qur'an yang ke {{ periode.ronde }}</h5>
			<h5>Total yang telah selesai ada {{ selesai }}</h5>
			<div class="tombol-bawah">
				<a href="/newjuz/{{periode.kloter_number}}"><button style="margin-left: 0px;" type="button" onclick={confirmDialog()} class="btn btn-primary button-putaran-baru">Putaran baru</button></a>
				<a href="/resetputaran/{{periode.kloter_number}}"><button style="margin-left: 10px;" type="button" class="btn btn-primary button-putaran-baru">Reset putaran</button></a>
				
			</div>
			<a href="/resetjuz/{{periode.kloter_number}}"><button style="margin-left: 0px;" type="button" class="btn btn-primary button-putaran-baru">Reset Juz</button></a>
			
			<div style="margin-top: 50px;"><a style="text-decoration: none; margin-top: 50px;" href="{% url 'kloter:list_kloter' %}">< Kembali</a></div>
			
		</div>
	
		<br>
	
	
		<div class="box1" style="width: 1060px; margin-left: 30px;">
			<div class="informasi">
				<h3 style="margin-top: 10px; color: #009DAE;">No.</h3>
				<h3 style="margin-left: 40px; margin-top: 10px; color: #009DAE;">Juz</h3>
				<h3 style="margin-left: 50px; margin-top: 10px; color: #009DAE;">Nama</h3>
				<h3 style="margin-left: 300px; margin-top: 10px; color: #009DAE;">Telepon</h3>
				<a href="{% url 'kloter:formperson' %}"><button style="height: 40px; width: 130px; margin-left: 160px; margin-top: 10px;" type="button" class="btn btn-primary">Tambah</button></a>
				
			</div>
	
			<hr>
			<div class="table-data">
				<div>
					{% for i in list_number %}
						<p style="margin-left: 30px; margin-top: 20px; padding-bottom: 36px; width: 0px;">{{ i }}</p>
						
					{% endfor %}
				</div>
	
				<div>
					{% for i in persons %}
						<div class="informasi">
							<p style="margin-left: 50px; color: rgb(175, 149, 0); font-weight: bold; width: 0px;">{{ i.no_juz }}</p>
							{% if i.selesai %}
								<div style="width: 400px;"><p style="margin-left: 80px; color:#76db3b; font-weight: bold;">{{ i.name }}</p></div>
							{% else %}
								<div style="width: 400px;"><p style="margin-left: 80px; color: rgb(196, 73, 73);">{{ i.name }}</p></div>
							{% endif %}
							<div style="width: 250px;"><p style="margin-left: 80px;">{{ i.telepon }}</p></div>
							<a href="/selesai/{{i.id}}"><button style="margin-left: 70px;" type="button" class="btn btn-success"><i class="fa fa-check"></i></button></a>
							<a href="/belumselesai/{{i.id}}"><button style="margin-left: 10px; color: white;" type="button" class="btn btn-warning"><i class="fa fa-close"></i></button></a>
							<a href="/editperson/{{i.id}}"><button style="margin-left: 10px;" type="button" class="btn btn-primary"><i class="fa fa-pencil"></i></button></a>
							<a href="/delete/{{i.id}}"><button style="margin-left: 10px;" type="button" class="btn btn-danger"><i class="fa fa-trash"></i></button></a>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
	<br>
	<br>
	<h4 style="margin-left: 50px; font-weight: bold;">Peserta yang belum selesai</h4>
	<div class="box-belum-selesai" style="width: 800px;">
		<div class="informasi" style="margin-left: 20px;">
			<h3 style="margin-top: 10px; color: #009DAE;">No.</h3>
			<h3 style="margin-left: 40px; margin-top: 10px; color: #009DAE;">Juz</h3>
			<h3 style="margin-left: 50px; margin-top: 10px; color: #009DAE;">Nama</h3>
			<h3 style="margin-left: 220px; margin-top: 10px; color: #009DAE;">Telepon</h3>
			
		</div>
		<hr>
		<div class="informasi">
			<div>
				{% for i in list_number_belum_selesai %}
					<p style="margin-left: 30px; margin-top: 20px; padding-bottom: 36px; width: 0px;">{{ i }}</p>
				{% endfor %}
			</div>
			<div>
				{% for i in persons_belum_selesai %}
					<div class="informasi" style="display: flex;">
						<p style="margin-left: 50px; color: rgb(175, 149, 0); font-weight: bold; width: 0px;">{{ i.no_juz }}</p>
						<div style="width: 320px;"><p style="margin-left: 80px; color: rgb(196, 73, 73);">{{ i.name }}</p></div>
						<div style="width: 250px;"><p style="margin-left: 80px;">{{ i.telepon }}</p></div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	<br>
	<br>
	<br>
<script>
	

	function confirmDialog() {
		no_kloter = document.getElementById("no_kloter").textContent;
		swal({
			title: "Berhasil",
			text: "Khataman putaran baru",
			type: 'success',
			showConfirmButton: false,
			timer: 2500
			}).then(function() {
				window.location = "/" + str(no_kloter);
		});
	}
</script>
</body>
</html>

kloter/templates/listkloter.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>List Kloter</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Mali:wght@500&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Mali:wght@500&family=Poppins&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/listkloter.css'%}">
</head>
<body style="margin:0;">
	<h1 style="color: #009DAE;" class="judul-page">Khotmul Qur'an</h1>
	<div class="container-page">
		{% for i in kloter_number2 %}
			<div><a href="/{{i.kloter_number}}"><button style="margin-left: 30px; margin-top: 30px;" type="button" class="btn btn-primary">Kloter {{ i.kloter_number }} ></button></a></div>
		{% endfor %}
	</div>

	<a href="{% url 'kloter:addkloter' %}"><button style="margin-top: 30px; margin-left: 30px;" type="button" class="btn btn-success">Tambah Kloter</button></a>
</body>
</html>